# Generated by Django 3.2.5 on 2022-03-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('IdUser', models.AutoField(primary_key=True, serialize=False)),
                ('Nick', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('fName', models.CharField(max_length=100)),
                ('sName', models.CharField(max_length=100)),
                ('PremiumStatus', models.BooleanField(default=False)),
                ('JoinDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('IdSinger', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=100)),
                ('sName', models.CharField(max_length=100)),
                ('Pseudonym', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('IdSong', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=101)),
                ('Time', models.IntegerField()),
                ('Performer', models.CharField(max_length=100)),
                ('CreationDate', models.DateTimeField()),
                ('Mp3', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Song_Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdSinger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='css.singer')),
                ('IdSong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='css.song')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdSong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='css.song')),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='css.member')),
            ],
        ),
    ]
