# Generated by Django 2.0.2 on 2022-05-16 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiumStatus', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('IdSinger', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=100)),
                ('sName', models.CharField(max_length=100)),
                ('Pseudonym', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('IdSong', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=101)),
                ('Time', models.CharField(blank=True, max_length=20)),
                ('Performer', models.CharField(max_length=100)),
                ('AddingDate', models.DateTimeField()),
                ('Mp3', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Song_Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdSinger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Singer')),
                ('IdSong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Song')),
            ],
        ),
        migrations.AddField(
            model_name='favouritesong',
            name='IdSong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Song'),
        ),
        migrations.AddField(
            model_name='favouritesong',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
