# Generated by Django 2.1.5 on 2022-06-08 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to='main.Account')),
                ('idUSer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_creator_set', to='main.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=101)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='favouritesong',
            name='IdSong',
        ),
        migrations.RemoveField(
            model_name='favouritesong',
            name='IdUser',
        ),
        migrations.RemoveField(
            model_name='song_singer',
            name='IdSinger',
        ),
        migrations.RemoveField(
            model_name='song_singer',
            name='IdSong',
        ),
        migrations.RenameField(
            model_name='singer',
            old_name='IdSinger',
            new_name='idSinger',
        ),
        migrations.RenameField(
            model_name='singer',
            old_name='Pseudonym',
            new_name='pseudonym',
        ),
        migrations.AddField(
            model_name='song',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='Mp3',
            field=models.FileField(upload_to='music'),
        ),
        migrations.AlterField(
            model_name='song',
            name='Time',
            field=models.DecimalField(decimal_places=2, max_digits=20, max_length=20),
        ),
        migrations.DeleteModel(
            name='FavouriteSong',
        ),
        migrations.DeleteModel(
            name='Song_Singer',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='main.Song'),
        ),
    ]
