# Generated by Django 2.1.5 on 2022-06-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220516_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
