# Generated by Django 4.0.3 on 2022-06-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_account_id_alter_friend_id_alter_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, max_length=20),
        ),
    ]
