# Generated by Django 4.0.3 on 2022-04-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Mp3',
            field=models.FileField(upload_to='musics'),
        ),
        migrations.AlterField(
            model_name='song',
            name='Time',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12),
        ),
    ]
