# Generated by Django 4.0.3 on 2022-04-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_song_mp3_alter_song_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Mp3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='Time',
            field=models.CharField(max_length=20),
        ),
    ]
