# Generated by Django 2.1.5 on 2022-06-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220605_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='Mp3',
            field=models.FileField(blank=True, null=True, upload_to='music'),
        ),
    ]
